allowBuilds:
  '@scarf/scarf': true
  better-sqlite3: true
  esbuild: true

onlyBuiltDependencies:
  - '@scarf/scarf'
  - better-sqlite3
  - esbuild

patchedDependencies:
  '@earendil-works/pi-ai@0.78.0': patches/@earendil-works__pi-ai@0.78.0.patch
